---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "quay/babysitters"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "quay/babysitters"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/toolkit"
    schedule:
      interval: "weekly"
    reviewers:
      - "quay/babysitters"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/updater/driver"
    schedule:
      interval: "weekly"
    reviewers:
      - "quay/babysitters"
    commit-message:
      prefix: "chore"
      include: "scope"
