[book]
title = "Claircore Documentation"
authors = ["Claircore Authors"]
description = "Additional documentation for Claircore."
src = "docs"
language = "en"

[build]
build-dir = "book"
create-missing = true

[output.html]
git-repository-url= "https://github.com/quay/claircore"

[preprocessor.godoc]
command = "go run github.com/quay/claircore/internal/cmd/mdbook-godoc"

[preprocessor.make_target]
command = "go run github.com/quay/claircore/internal/cmd/mdbook-make_target"

[preprocessor.injecturls]
command = "go run github.com/quay/claircore/internal/cmd/mdbook-injecturls"
