[book]
title = "Claircore Documentation"
authors = ["Claircore Authors"]
description = "Additional documentation for Claircore."
src = "docs"
language = "en"

[build]
build-dir = "book"
create-missing = true

[output.html]
git-repository-url= "https://github.com/quay/claircore"

[preprocessor.godoc]
command = "go run docs/godoc.go"

[preprocessor.make_target]
command = "go run docs/make_target.go"

[preprocessor.injecturls]
command = "go run docs/injecturls.go"
