---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  config:
    runs-on: ubuntu-latest
    outputs:
      go_versions: ${{ steps.config.outputs.go_versions }}
    steps:
      - id: config
        run: |
          echo 'go_versions=["1.20","1.19"]' >> $GITHUB_OUTPUT

  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: commit check
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: |
            ^(.*):\s*(.*)\n.*$
          error: 'Commit must begin with <scope>: <subject>'
          flags: 'gm'
          excludeTitle: true
          excludeDescription: true
          checkAllCommitMessages: true
          accessToken: ${{ secrets.GITHUB_TOKEN }}

  tidy:
    needs: ['config']
    name: Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ fromJSON(needs.config.outputs.go_versions)[0] }}
      - name: Go Tidy
        run: go mod tidy
      - name: Git Diff
        run: git diff --exit-code

  build-documentation:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.3.5'
      - name: mdBook Build
        run: mdbook build

  tests:
    needs: ['config']
    name: Tests
    runs-on: ubuntu-latest
    env:
      POSTGRES_CONNECTION_STRING: "host=localhost port=5432 user=claircore dbname=claircore password=password sslmode=disable"
    strategy:
      fail-fast: false
      matrix:
        go: ${{ fromJSON(needs.config.outputs.go_versions) }}
    steps:
      - name: Database setup
        run: |
          set -e
          sudo systemctl start postgresql.service
          sudo -u postgres createuser -d -r -s claircore
          sudo -u postgres psql -c "ALTER ROLE claircore WITH PASSWORD 'password';"
          sudo -u postgres createdb -O claircore claircore
          psql -c 'SELECT version();' "$POSTGRES_CONNECTION_STRING" 
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Cache misc testdata
        uses: actions/cache@v3
        with:
          key: testdata-${{ hashFiles('**/*_test.go') }}
          restore-keys: |
            testdata-
          path: |
            **/testdata/*.layer
            **/testdata/*.tar
            **/testdata/*.tar.gz
      - name: Tests
        run: >
          find .
          -name .git -prune -o
          -name testdata -prune -o
          -name go.mod -execdir go test -race -tags integration ./... \;
