---
name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'the branch to prepare the release against'
        required: true
        default: 'main'
      tag:
        description: 'the tag to be released'
        required: true

jobs:
  prepare:
    name: Prepare Release
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Changelog
        run: |
          .github/scripts/changelog-edit -s
          .github/scripts/changelog-update "${{ github.event.inputs.tag }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          title: "${{ github.event.inputs.tag }} Changelog Bump"
          body: "This is an automated changelog commit."
          commit-message: "chore: ${{ github.event.inputs.tag }} changelog bump"
          branch: "ready-${{ github.event.inputs.tag }}"
          signoff: true
          delete-branch: true
